version: '3.6'

services:

  eureka:
    image: eureka
    ports:
      - 1001:1001
    networks:
      - eureka-server
  gateway:
    image: gateway
    ports:
      - 1000:1000
    networks:
      - gateway-server
  customer:
    image: customer
    ports:
      - 1002:1002
    depends_on:
      - eureka
    networks:
      - customer-service
  product:
    image: product
    ports:
      - 1003:1003
    depends_on:
      - eureka
    networks:
      - product-service

networks:
  eureka-server: { }
  gateway-server: { }
  customer-service: { }
  product-service: { }