version: '3.8'

services:
  eureka-server:
    container_name: eureka-server
    build:
      context: ./spring-boot-eureka-discovery
      dockerfile: ./docker-images/Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    ports:
      - "8761:8761"
  cloud-gateway:
    container_name: cloud-gateway
    build:
      context: ./spring-boot-cloud-gateway
      dockerfile: ./docker-images/Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    ports:
      - "1000:1000"
  customer-service:
    container_name: customer-service
    build:
      context: ./spring-boot-customer-service
      dockerfile: ./docker-images/Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    ports:
      - "1002:1002"
  product-service:
    container_name: product-service
    build:
      context: ./spring-boot-product-service
      dockerfile: ./docker-images/Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    ports:
      - "1003:1003"