apiVersion: v1
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: eureka-deployment
spec:
  selector:
      app: eurekalabel
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761