server:
  port: 8761
spring:
  application:
    name: gateway-server
eureka:
  client:
    health-check:
      enabled: true
    register-with-eureka: false
    fetch-registry: false
    #service-url:
      #defaultZone: http://192.168.0.176:1001/eureka
