apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: product-deployment
  labels:
    app: productlabel
spec:
  replicas: 1 # Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: productlabel
  template:
    metadata:
      labels:
        app: productlabel
    spec:
      containers:
        - name: product
          image: product:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          env:
            - name: eureka.client.service-url.defaultZone
              value: http://10.97.211.158:8761/eureka
          ports:
            - containerPort: 1003 # The port that the container is running on in the cluster