apiVersion: v1
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: product-deployment
spec:
  selector:
      app: productlabel
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1003
      targetPort: 1003