server:
  port: 1002
spring:
  application:
    name: customer-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  batch:
    job:
      enabled: false
  jpa:
    properties:
      format_sql: true
      show-sql: true
eureka:
  client:
    health-check:
      enabled: true
    #service-url:
      #defaultZone: http://192.168.0.176:1001/eureka
    healthcheck:
      enabled:
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      test-resilience4j:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 10
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      test-resilience4j:
        maxRetryAttempts: 5
        waitDuration: 10s
  ratelimiter:
    instances:
      test-resilience4j:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 3s